# -*- coding: utf-8 -*-
"""01_Time_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpMvUt7ik6hBNmmvAXV8j26nThlxRY92

1) Given number of minutes, convert it into human readable form.
Example :
- 130 becomes “2 hrs 10 minutes”
- 110 becomes “1hr 50minutes”
"""

def minutes_to_hours_minutes(total_minutes):
    hours = total_minutes // 60
    remaining_minutes = total_minutes % 60
    return f"{hours} hrs {remaining_minutes} minutes"

print(minutes_to_hours_minutes(130))
print(minutes_to_hours_minutes(110))
print(minutes_to_hours_minutes(45))