# -*- coding: utf-8 -*-
"""02_Remove_Duplicates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwtQoD9pvjdJrUQtP9Gq8gW2jBHU_66R

2) You are given a string, remove all the duplicates and print the unique string.Use loop in the python.
"""

def remove_duplicates(s):
    result = ""
    for char in s:
        if char not in result:
            result += char
    return result


print(remove_duplicates("programming"))
print(remove_duplicates("banana"))
print(remove_duplicates("aabbccdd"))